// we want the subsequence in the lexographically sorted order 

/*
Given a string of length n, generate all of its subsequences.

A subsequence of a given string (sequence) is a string (sequence) that is generated by
removing zero or more characters from the given string (sequence) without changing its
order.

Example

	Input : inp[] = "abc"
	Output: ["", "c", "b", "bc", "a", "ac", "ab", "abc"]

Constraints

  1 < n < 10

*/

#include<iostream>
#include<set>

using namespace std;

void f(char inp[], char out[], int i, int j , set<string> & s) {

	// base case
	if (inp[i] == '\0') {
		out[j] = '\0';
	 // cout << out << endl;
     string str(out); // create a string str , and initialize the string with out array

     //s.insert(str);// s is a set of string type , so insert string in it 
     // OR
     s.insert(string(out));
		return;
	}

	// recursive case

	// f(i, j) = take a sequence of decisions for char in the inp[i...n-1] s.t. next free index in the out[] is j

	// take a decision for inp[i]

	// option 1 : include inp[i] in the out[]
	out[j] = inp[i];
	f(inp, out, i + 1, j + 1 , s);

	// option 2 : exclude inp[i] from the out[]
	f(inp, out, i + 1, j , s);

}

int main() {

	char inp[] = "abc";
	char out[10];
    set<string> s ;

	f(inp, out, 0, 0 , s);

    cout<<"size of set : "<<s.size()<<endl;
    for( auto it : s)
    {
        cout<<it<<endl;
    }

	return 0;
}